// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package interfaces

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function for the type MockLogger
func (_mock *MockLogger) Error(err error, msg string) {
	_mock.Called(err, msg)
	return
}

// MockLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type MockLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - err error
//   - msg string
func (_e *MockLogger_Expecter) Error(err interface{}, msg interface{}) *MockLogger_Error_Call {
	return &MockLogger_Error_Call{Call: _e.mock.On("Error", err, msg)}
}

func (_c *MockLogger_Error_Call) Run(run func(err error, msg string)) *MockLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLogger_Error_Call) Return() *MockLogger_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Error_Call) RunAndReturn(run func(err error, msg string)) *MockLogger_Error_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function for the type MockLogger
func (_mock *MockLogger) Info(msg string, keys ...interface{}) {
	if len(keys) > 0 {
		_mock.Called(msg, keys)
	} else {
		_mock.Called(msg)
	}

	return
}

// MockLogger_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type MockLogger_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - msg string
//   - keys ...interface{}
func (_e *MockLogger_Expecter) Info(msg interface{}, keys ...interface{}) *MockLogger_Info_Call {
	return &MockLogger_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{msg}, keys...)...)}
}

func (_c *MockLogger_Info_Call) Run(run func(msg string, keys ...interface{})) *MockLogger_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []interface{}
		var variadicArgs []interface{}
		if len(args) > 1 {
			variadicArgs = args[1].([]interface{})
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockLogger_Info_Call) Return() *MockLogger_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Info_Call) RunAndReturn(run func(msg string, keys ...interface{})) *MockLogger_Info_Call {
	_c.Run(run)
	return _c
}

// NewMockRedisDB creates a new instance of MockRedisDB. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRedisDB(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRedisDB {
	mock := &MockRedisDB{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRedisDB is an autogenerated mock type for the RedisDB type
type MockRedisDB struct {
	mock.Mock
}

type MockRedisDB_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRedisDB) EXPECT() *MockRedisDB_Expecter {
	return &MockRedisDB_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockRedisDB
func (_mock *MockRedisDB) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRedisDB_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockRedisDB_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockRedisDB_Expecter) Ping(ctx interface{}) *MockRedisDB_Ping_Call {
	return &MockRedisDB_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockRedisDB_Ping_Call) Run(run func(ctx context.Context)) *MockRedisDB_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRedisDB_Ping_Call) Return(err error) *MockRedisDB_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRedisDB_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockRedisDB_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDBPool creates a new instance of MockDBPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDBPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDBPool {
	mock := &MockDBPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDBPool is an autogenerated mock type for the DBPool type
type MockDBPool struct {
	mock.Mock
}

type MockDBPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDBPool) EXPECT() *MockDBPool_Expecter {
	return &MockDBPool_Expecter{mock: &_m.Mock}
}

// Ping provides a mock function for the type MockDBPool
func (_mock *MockDBPool) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDBPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockDBPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockDBPool_Expecter) Ping(ctx interface{}) *MockDBPool_Ping_Call {
	return &MockDBPool_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockDBPool_Ping_Call) Run(run func(ctx context.Context)) *MockDBPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDBPool_Ping_Call) Return(err error) *MockDBPool_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDBPool_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *MockDBPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}
